language: node_js
node_js:
  - '11'
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  target-branch: master
  cleanup: true
  local-dir: ./build
  repo: HondryTravis/HondryTravis.github.io
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
