language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  target-branch: master
  cleanup: true
  local-dir: docs/.vuepress/dist
  repo: HondryTravis/HondryTravis.github.io
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
